# Generated by Django 4.2.13 on 2024-07-11 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_status', models.BooleanField(default=True, verbose_name='System Status')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
            options={
                'db_table': 'SystemStatus',
            },
        ),
    ]
